apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
name: go-goa-gone
namespace: argocd
labels:
  owner: "platform-team"
spec:
project: demo-backstage-uat
source:
  repoURL: https://github.com/chandrashekhar-appointy/platform-middleclients-gitops.git
  targetRevision: HEAD
  path: charts/omnix
  helm:
    valueFiles:
      - ../../tenants/demo-backstage-uat/argocd/values/go-goa-gone/values.yaml
destination:
  server: https://kubernetes.default.svc
  namespace: backstage
syncPolicy:
  automated:
    prune: true
    selfHeal: true
    allowEmpty: false
  syncOptions:
    - CreateNamespace=true
  retry:
    limit: 5
    backoff:
      duration: 5s
      factor: 2
      maxDuration: 3m