apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: testing-goooo
  namespace: argocd
  labels:
    owner: "platform-team"
spec:
  project: demo-backstage-uat
  source:
    repoURL: https://github.com/chandrashekhar-appointy/platform-middleclients-gitops
    targetRevision: main
    path: charts/Omnix
    helm:
      valueFiles:
        - ../../tenants/demo-backstage-uat/argocd/values/testing-goooo.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: uat
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m